parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: graph_sample
    database_user: root
    database_password: ellika
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 90e37e1efd4663283d6ba848718a206d087ddfb2

