<?php

namespace Viz\DataVizBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EdgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdgesRepository extends EntityRepository
{
    public function getClusterEdges($mod){
        $qb=$this->createQueryBuilder('es')
            ->select('es.id','es.source','es.target','es.label','es.weight','es.timesta','es.retweetCount','es.rtw_id')
            ->where('es.modu=?1')
            ->setParameter(1,$mod);

        $e= $qb->getQuery()
            ->getResult();

        $edges=array();
        $attributes=array();
        foreach($e as $edge){
            $attributes['weight']=$edge['weight'];
            $attributes['tmstmp']=$edge['timesta'];
            $attributes['retweetCount']=$edge['retweetCount'];
            $attributes['rtw_id']=$edge['rtw_id'];
            $edges[]=array("id"=>$edge['id'],"source"=>$edge['source'],"target"=>$edge['target'],
                "label"=>$edge['label'],"attributes"=>[$attributes]);
}

        return $edges;

    }
    public function getEdgesByHashtag(array $h){

        $sb = $this->getEntityManager()->getRepository('VizDataVizBundle:TweetText')
            ->getUserId($h);


        $qb=$this->createQueryBuilder('es')
            ->select('es.source','es.target','es.id','es.label','es.weight','es.timesta','es.retweetCount','es.rtw_id') /////// ftiaksimo opws panw!!!!
            ->where('es.source In (:nodes)')
            ->andWhere('es.target In (:nodes)')
            ->setParameter('nodes',$sb);

      $ht= $qb->getQuery()
            ->getResult();

        $edges=array();
        $attributes=array();
        foreach($ht as $e){
            $attributes['weight']=$e['weight'];
            $attributes['tmstmp']=$e['timesta'];
           $attributes['retweetCount']=$e['retweetCount'];
            $attributes['rtw_id']=$e['rtw_id'];
            $edges[]=array("id"=>$e['id'],"source"=>$e['source'],"target"=>$e['target'],
                "label"=>$e['label'],"attributes"=>[$attributes]);

        }

        return $edges;

    }
}
