<?php

namespace Viz\DataVizBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MetaEdgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaEdgesRepository extends EntityRepository
{
    public function getMetaEdges(){

        $sb = $this->getEntityManager()->getRepository('VizDataVizBundle:MetaNodes')
            ->getMetaNodes();


        $qb=$this->createQueryBuilder('me')
            ->select( 'distinct me.source','me.target','me.id')
            ->where('me.source In (:nodes)')
            ->andWhere('me.target In (:nodes)')
            ->setParameter('nodes',$sb)
            ->groupBy('me.source','me.target');

        $me=$qb->getQuery()
            ->getResult();


        $metaedges=array();
        foreach($me as $m){
            $metaedges[]=array("id"=>$m['id'],"source"=>$m['source'],"target"=>$m['target']);
        }

        return $metaedges;
    }


}
